/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import static java.lang.Thread.sleep;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Akila Jayasinghe
 */
public class Member extends javax.swing.JFrame{

    /**
     * Creates new form Home
     */
    
    public void clock(){
        
        Thread tclock=new Thread()
        {
             public void run(){
                try {
                        for(;;){
                             DateFormat df = new SimpleDateFormat("hh:mm:ss");
                             Date d=new Date();
                             String s=df.format(d);
                             clock.setText(s);    
                             
                             DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
                             String s1=df1.format(d);
                             date.setText(s1); 
                             
                             sleep(1000);
                    
                        }
                } catch (Exception e) {
                    e.printStackTrace();;
                }
            }
        };
        
        tclock.start();
        
        
        
    }
    public Member() {
        initComponents();
        
        Toolkit tk=Toolkit.getDefaultToolkit();
            int xsize=(int) tk.getScreenSize().getWidth();
            int ysize=(int) tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
        clock();
        member.setBackground(new Color(76, 157, 255));
      tableload();
      
    }
    
    public void tableload(){
        library.read("member.txt");
        memberclass [] memb=library.getlibrary().getMembers().getallmembers();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for(memberclass member:memb){
            model.addRow(new Object[]{member.getmemnum(),member.getmembername(),member.getBooksOnLoan().getSize()});
        }
        
       int c=jTable1.getRowCount();
        int y=(int) jTable1.getValueAt(c-1, 0);
        int ac=y+1;
        memnum.setText(Integer.toString(ac));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        memnum = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sname = new javax.swing.JRadioButton();
        snumber = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        book = new javax.swing.JLabel();
        member = new javax.swing.JLabel();
        return_book = new javax.swing.JLabel();
        issue_book = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Member Details");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 270, -1));

        clock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 150, 30));

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 40, 150, 30));

        jLabel5.setBackground(new java.awt.Color(51, 153, 255));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1000, 80));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Member Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel9.setText("Name");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("Member Number");

        memnum.setEditable(false);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akila Jayasinghe\\Documents\\NetBeansProjects\\Library System\\Image\\memberadd.png")); // NOI18N
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akila Jayasinghe\\Documents\\NetBeansProjects\\Library System\\Image\\memberupdate.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akila Jayasinghe\\Documents\\NetBeansProjects\\Library System\\Image\\deletemember.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akila Jayasinghe\\Documents\\NetBeansProjects\\Library System\\Image\\clear.png")); // NOI18N
        jButton5.setText("jButton2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(memnum, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memnum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 480, 540));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Member", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Constantia", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Member ID", "Name", "No. of Books Borrowed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 204, 204));
        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttonGroup1.add(sname);
        sname.setText("Name");
        sname.setOpaque(false);

        buttonGroup1.add(snumber);
        snumber.setText("Member ID");
        snumber.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(snumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sname)
                    .addComponent(snumber))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 480, 540));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 98, 300, -1));

        book.setBackground(new java.awt.Color(0, 102, 255));
        book.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        book.setForeground(new java.awt.Color(255, 255, 255));
        book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        book.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akila Jayasinghe\\Documents\\NetBeansProjects\\Library System\\Image\\bookinfo.png")); // NOI18N
        book.setText("Book Details");
        book.setAlignmentX(0.5F);
        book.setIconTextGap(30);
        book.setOpaque(true);
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookMouseExited(evt);
            }
        });
        getContentPane().add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 350, 60));

        member.setBackground(new java.awt.Color(0, 102, 255));
        member.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        member.setForeground(new java.awt.Color(255, 255, 255));
        member.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        member.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akila Jayasinghe\\Documents\\NetBeansProjects\\Library System\\Image\\addmember.png")); // NOI18N
        member.setText("Member Details");
        member.setAlignmentX(0.5F);
        member.setIconTextGap(30);
        member.setOpaque(true);
        getContentPane().add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 350, 60));

        return_book.setBackground(new java.awt.Color(0, 102, 255));
        return_book.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        return_book.setForeground(new java.awt.Color(255, 255, 255));
        return_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        return_book.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akila Jayasinghe\\Documents\\NetBeansProjects\\Library System\\Image\\return.png")); // NOI18N
        return_book.setText("Return Book");
        return_book.setAlignmentX(0.5F);
        return_book.setIconTextGap(30);
        return_book.setOpaque(true);
        return_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                return_bookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                return_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                return_bookMouseExited(evt);
            }
        });
        getContentPane().add(return_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 350, 60));

        issue_book.setBackground(new java.awt.Color(0, 102, 255));
        issue_book.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        issue_book.setForeground(new java.awt.Color(255, 255, 255));
        issue_book.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        issue_book.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akila Jayasinghe\\Documents\\NetBeansProjects\\Library System\\Image\\Issue_book.png")); // NOI18N
        issue_book.setText("Issue Book");
        issue_book.setAlignmentX(0.5F);
        issue_book.setIconTextGap(30);
        issue_book.setOpaque(true);
        issue_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issue_bookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issue_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issue_bookMouseExited(evt);
            }
        });
        getContentPane().add(issue_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 350, 60));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Library Assistant");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 40));

        jLabel2.setBackground(new java.awt.Color(0, 102, 255));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 700));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akila Jayasinghe\\Documents\\NetBeansProjects\\Library System\\Image\\bg.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issue_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issue_bookMouseEntered
        issue_book.setBackground(new Color(46, 140, 254));
    }//GEN-LAST:event_issue_bookMouseEntered

    private void issue_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issue_bookMouseExited
        issue_book.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_issue_bookMouseExited

    private void return_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_bookMouseEntered
        return_book.setBackground(new Color(46, 140, 254));
    }//GEN-LAST:event_return_bookMouseEntered

    private void return_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_bookMouseExited
        return_book.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_return_bookMouseExited

    private void bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseEntered
        book.setBackground(new Color(46, 140, 254));
    }//GEN-LAST:event_bookMouseEntered

    private void bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseExited
        book.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_bookMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Integer ID =new Integer(memnum.getText());
        String Name= name.getText();
        
        try {
            library.read("member.txt");
            library.getlibrary().getMembers().addMember(new memberclass(Name, ID));
            
           library.write("member.txt");
           clear();
           tableload();
           JOptionPane.showMessageDialog(rootPane, "Member Successfully Added");
           
        } catch (Exception e) {
            System.out.println("button error " +e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        library.read("member.txt");
        String sea=search.getText();
        if(sname.isSelected()){
            memberclass mem1b=library.getlibrary().getMembers().getMemberFromName(sea);
            
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            
                model.addRow(new Object[]{mem1b.getmemnum(),mem1b.getmembername(),mem1b.getBooksOnLoan().getSize()});
            
        }
        else if(snumber.isSelected()){
            Integer i=new Integer(sea);
             memberclass mem1b=library.getlibrary().getMembers().getMemberFromNumber(i);
            
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            
                model.addRow(new Object[]{mem1b.getmemnum(),mem1b.getmembername(),mem1b.getBooksOnLoan().getSize()});
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Please Select Search Method");
            tableload();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void issue_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issue_bookMouseClicked
       IssueBook i= new IssueBook();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_issue_bookMouseClicked

    private void return_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_bookMouseClicked
        ReturnBook i= new ReturnBook();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_return_bookMouseClicked

    private void bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseClicked
        Book i= new Book();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bookMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        clear();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int x=JOptionPane.showConfirmDialog(null,"Do you really want to update ?");
        
        if(x==0){
            Integer ID =new Integer(memnum.getText());
            String Name= name.getText();

            library.read("member.txt");
            memberclass m=library.getlibrary().getMembers().getMemberFromNumber(ID);
            library.getlibrary().getMembers().removeMember(m);
            library.getlibrary().getMembers().addMember(new memberclass(Name, ID));
            library.write("member.txt");
            clear();
            tableload();
            JOptionPane.showMessageDialog(rootPane,"Successfully upddated");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int x=JOptionPane.showConfirmDialog(null,"Do you really want to Delete ?");
        
        if(x==0){ 
            Integer ID =new Integer(memnum.getText());
            String Name= name.getText();

            library.read("member.txt");
            memberclass m=library.getlibrary().getMembers().getMemberFromNumber(ID);
            library.getlibrary().getMembers().removeMember(m);
            library.write("member.txt");
            clear();
            tableload();
            JOptionPane.showMessageDialog(this,"Successfully Deleted");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int x=jTable1.getSelectedRow();
        memnum.setText(jTable1.getValueAt(x, 0).toString());
        name.setText(jTable1.getValueAt(x, 1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    public void clear(){
        name.setText("");
        memnum.setText("");
        tableload();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel date;
    private javax.swing.JLabel issue_book;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel member;
    private javax.swing.JTextField memnum;
    private javax.swing.JTextField name;
    private javax.swing.JLabel return_book;
    private javax.swing.JTextField search;
    private javax.swing.JRadioButton sname;
    private javax.swing.JRadioButton snumber;
    // End of variables declaration//GEN-END:variables
}
